// This type is generated by Supabase CLI
// For now, define basic types. Run `supabase gen types typescript` to generate full types
//
// IMPORTANT: This type definition must include all schemas used by the Supabase client:
// - public (your tables)
// - realtime (for subscriptions)
// - storage (for file storage)
// - auth (for authentication)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      thesis_check_records: {
        Row: {
          id: string
          person_name: string
          file_name: string
          file_content: string
          created_at: string
          status_color: string
        }
        Insert: {
          id?: string
          person_name: string
          file_name: string
          file_content: string
          status_color?: string
        }
        Update: {
          id?: string
          person_name?: string
          file_name?: string
          file_content?: string
          status_color?: string
        }
      }
    }
    Functions: {}
    Enums: {}
  }
  realtime: {
    Tables: {}
    Views: {}
    Functions: {}
    Enums: {}
  }
  storage: {
    Tables: {
      buckets: {
        Row: {
          id: string
          name: string
          owner: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          owner?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          owner?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      objects: {
        Row: {
          id: string
          bucket_id: string
          name: string
          owner: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          bucket_id: string
          name: string
          owner?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          bucket_id?: string
          name?: string
          owner?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Functions: {}
  }
  auth: {
    Tables: {
      users: {
        Row: {
          id: string
          aud: string
          role: string | null
          email: string | null
          encrypted_password: string | null
          email_confirmed_at: string | null
          invited_at: string | null
          confirmation_token: string | null
          recovery_token: string | null
          email_change_token_new: string | null
          phone: string | null
          phone_confirmed_at: string | null
          phone_change_token: string | null
          last_sign_in_at: string | null
          raw_app_meta_data: Json
          raw_user_meta_data: Json
          is_super_admin: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          aud?: string
          role?: string | null
          email?: string | null
          encrypted_password?: string | null
          email_confirmed_at?: string | null
          invited_at?: string | null
          confirmation_token?: string | null
          recovery_token?: string | null
          email_change_token_new?: string | null
          phone?: string | null
          phone_confirmed_at?: string | null
          phone_change_token?: string | null
          last_sign_in_at?: string | null
          raw_app_meta_data?: Json
          raw_user_meta_data?: Json
          is_super_admin?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          aud?: string
          role?: string | null
          email?: string | null
          encrypted_password?: string | null
          email_confirmed_at?: string | null
          invited_at?: string | null
          confirmation_token?: string | null
          recovery_token?: string | null
          email_change_token_new?: string | null
          phone?: string | null
          phone_confirmed_at?: string | null
          phone_change_token?: string | null
          last_sign_in_at?: string | null
          raw_app_meta_data?: Json
          raw_user_meta_data?: Json
          is_super_admin?: boolean
          created_at?: string
          updated_at?: string
        }
      }
    }
    Functions: {}
  }
}
